remote_theme: daviddarnes/alembic

theme: jekyll-theme-tactile

navigation_header:
  Home: /
  Project 1: https://bergren1.github.io/Project1/
  Project 2: https://bergren1.github.io/Project2/
  Project 3: https://bergren1.github.io/Project3/
  Project 4: https://bergren1.github.io/Ges-486-Final-Project/
